name: Cypress Testing

on:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ secrets.TEST_USER_NAME }}  # Use secrets for sensitive data
      PASSWORD: ${{ secrets.TEST_PASSWORD }}      # Use secrets for sensitive data
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Additional Packages
        run: |
          npm install cypress --save-dev
          npm install xlsx --save
          npm install axios --save
          npm install @cypress/code-coverage --save-dev
          npm install cypress-file-upload --save-dev

      - name: Run Cypress Tests
        run: npx cypress run --spec "cypress/e2e/*.cy.js" --config-file=./cypress.config.cjs  
