name: Cypress Testing

on:
  workflow_dispatch:

jobs:
  
  production-plan:
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ vars.TEST_USER_NAME }}
      PASSWORD: ${{ vars.TEST_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress
        run: 
          npm install cypress --save-dev
          npm install xlsx

      - name: Run Cypress test file
        run: npx cypress run --spec "cypress/e2e/*.cy.js" --config-file=./cypress.config.cjs
