name: Cypress Testing

on:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ vars.TEST_USER_NAME }}
      PASSWORD: ${{ vars.TEST_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Install XLSX
        run: npm install xlsx --save

      - name: Install Axios
        run: npm install axios --save

      - name: Install Additional Cypress Plugins optional 
        run: |
          npm install @cypress/code-coverage --save-dev
          npm install cypress-file-upload --save-dev

      - name: Run Cypress Test Files
        run: npx cypress run --spec "cypress/e2e/*.cy.js" --config-file=./cypress.config.cjs
