name: Cypress Testing

on:
  workflow_dispatch:

jobs:
  
  cypress:
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ vars.TEST_USER_NAME }}
      PASSWORD: ${{ vars.TEST_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Cypress
        run: 
          npm install cypress --save-dev
          npm install xlsx
          npm install axios



      - name: Run Cypress test file
        run: npx cypress run --spec "cypress/e2e/*.cy.js" --config-file=./cypress.config.cjs
